const $=s=>document.querySelector(s), enc=new TextEncoder(), dec=new TextDecoder();
const DB='anubis-vault', STORE='vault'; let db,key,items=[],idleTimer,imageData='';
const kinds={password:'账号密码',token:'API Token',note:'私密文字',image:'私密图片'};
function openDB(){return new Promise((ok,no)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>r.result.createObjectStore(STORE);r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})}
function get(k){return new Promise((ok,no)=>{const r=db.transaction(STORE).objectStore(STORE).get(k);r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})}
function put(k,v){return new Promise((ok,no)=>{const r=db.transaction(STORE,'readwrite').objectStore(STORE).put(v,k);r.onsuccess=ok;r.onerror=()=>no(r.error)})}
const b64=b=>btoa(String.fromCharCode(...new Uint8Array(b))), unb64=s=>Uint8Array.from(atob(s),c=>c.charCodeAt(0));
async function derive(password,salt){const raw=await crypto.subtle.importKey('raw',enc.encode(password),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:310000,hash:'SHA-256'},raw,{name:'AES-GCM',length:256},false,['encrypt','decrypt'])}
async function encrypt(value,k=key){const iv=crypto.getRandomValues(new Uint8Array(12)),data=await crypto.subtle.encrypt({name:'AES-GCM',iv},k,enc.encode(JSON.stringify(value)));return{iv:b64(iv),data:b64(data)}}
async function decrypt(box,k=key){return JSON.parse(dec.decode(await crypto.subtle.decrypt({name:'AES-GCM',iv:unb64(box.iv)},k,unb64(box.data))))}
function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),2200)}
async function init(){db=await openDB();const meta=await get('meta');if(meta){$('#welcomeTitle').textContent='解锁保险箱';$('#welcomeText').textContent='输入主密码，在此设备上解密你的秘密。';$('#confirmWrap').classList.add('hidden');$('#unlockSubmit').textContent='解锁';}else $('#confirmPassword').required=true}
$('#unlockForm').onsubmit=async e=>{e.preventDefault();const p=$('#masterPassword').value,meta=await get('meta');try{if(!meta){if(p!==$('#confirmPassword').value)return toast('两次密码不一致');const salt=crypto.getRandomValues(new Uint8Array(16));key=await derive(p,salt);await put('meta',{version:1,salt:b64(salt),check:await encrypt({valid:true})});await put('items',await encrypt([]));}else{key=await derive(p,unb64(meta.salt));await decrypt(meta.check)}items=await decrypt(await get('items'));$('#masterPassword').value='';showVault();}catch{key=null;toast('主密码错误，无法解密')}};
function showVault(){$('#welcome').classList.add('hidden');$('#vault').classList.remove('hidden');$('#lockBtn').classList.remove('hidden');render();resetIdle();if(typeof syncVault==='function')syncVault(true)}
function lock() {key=null;items=[];imageData='';$('#vault').classList.add('hidden');$('#lockBtn').classList.add('hidden');$('#welcome').classList.remove('hidden');$('#masterPassword').focus();clearTimeout(idleTimer)}
function resetIdle(){if(!key)return;clearTimeout(idleTimer);idleTimer=setTimeout(()=>{lock();toast('因长时间未操作，保险箱已锁定')},5*60*1000)}
['pointerdown','keydown'].forEach(x=>addEventListener(x,resetIdle));$('#lockBtn').onclick=lock;
function render(){const active=items.filter(x=>!x._deleted),q=$('#search').value.toLowerCase(),shown=active.filter(x=>[x.title,x.kind,x.tags,x.username].join(' ').toLowerCase().includes(q));$('#itemCount').textContent=active.length;$('#empty').classList.toggle('hidden',active.length>0);$('#cards').innerHTML=shown.map(x=>`<article class="card" data-id="${x.id}"><span class="type">${kinds[x.kind]}</span><h3>${escapeHtml(x.title)}</h3><p>${x.kind==='image'?'已加密保存图片':x.username?escapeHtml(x.username):'••••••••••••'}</p><div>${(x.tags||'').split(',').filter(Boolean).map(t=>`<span class="tag">${escapeHtml(t.trim())}</span>`).join('')}</div></article>`).join('');document.querySelectorAll('.card').forEach(c=>c.onclick=()=>edit(c.dataset.id))}
const escapeHtml=s=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));$('#search').oninput=render;
function edit(id){const x=items.find(v=>v.id===id);$('#secretForm').reset();$('#editId').value=x?.id||'';$('#dialogTitle').textContent=x?'查看 / 编辑秘密':'保存新秘密';$('#deleteBtn').classList.toggle('hidden',!x);['kind','title','tags','username','content'].forEach(k=>$('#'+k).value=x?.[k]||'');imageData=x?.image||'';updateKind();if(imageData){$('#preview').src=imageData;$('#preview').classList.remove('hidden')}else $('#preview').classList.add('hidden');$('#editor').showModal()}
$('#addBtn').onclick=()=>edit();$('#closeDialog').onclick=$('#cancelBtn').onclick=()=>$('#editor').close();
function updateKind(){const k=$('#kind').value;$('#usernameWrap').classList.toggle('hidden',!['password','token'].includes(k));$('#imageWrap').classList.toggle('hidden',k!=='image');$('#content').required=k!=='image'}$('#kind').onchange=updateKind;
$('#imageInput').onchange=e=>{const f=e.target.files[0];if(!f)return;if(f.size>5e6)return toast('图片不能超过 5 MB');const r=new FileReader;r.onload=()=>{imageData=r.result;$('#preview').src=imageData;$('#preview').classList.remove('hidden')};r.readAsDataURL(f)};
$('#secretForm').onsubmit=async e=>{e.preventDefault();const id=$('#editId').value||crypto.randomUUID(),old=items.find(x=>x.id===id),x={id,kind:$('#kind').value,title:$('#title').value.trim(),tags:$('#tags').value.trim(),username:$('#username').value,content:$('#content').value,image:imageData,updatedAt:new Date().toISOString(),createdAt:old?.createdAt||new Date().toISOString()};if(x.kind==='image'&&!x.image)return toast('请选择一张图片');items=old?items.map(v=>v.id===id?x:v):[x,...items];await put('items',await encrypt(items));$('#editor').close();render();toast('已加密保存');if(typeof scheduleSync==='function')scheduleSync()};
$('#deleteBtn').onclick=async()=>{if(!confirm('确定删除这条秘密？已同步设备也会删除，但历史版本仍可恢复。'))return;const now=new Date().toISOString(),id=$('#editId').value;items=items.map(x=>x.id===id?{id,_deleted:true,updatedAt:now,createdAt:x.createdAt}:x);await put('items',await encrypt(items));$('#editor').close();render();toast('已删除');if(typeof scheduleSync==='function')scheduleSync()};
$('#exportBtn').onclick=async()=>{const data={format:'anubis-backup',exportedAt:new Date().toISOString(),meta:await get('meta'),items:await get('items')},a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data)],{type:'application/json'}));a.download=`anubis-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href);toast('加密备份已导出')};
$('#importInput').onchange=async e=>{try{const data=JSON.parse(await e.target.files[0].text());if(data.format!=='anubis-backup'||!data.meta||!data.items)throw Error();if(!confirm('导入会替换当前保险箱。确定继续？'))return;await put('meta',data.meta);await put('items',data.items);toast('备份已导入，请重新解锁');lock();location.reload()}catch{toast('备份文件无效')}finally{e.target.value=''}};init();
