'use strict';
let syncBusy=false,syncTimer,inviteTimer;
const randomHex=n=>[...crypto.getRandomValues(new Uint8Array(n))].map(x=>x.toString(16).padStart(2,'0')).join('');
const cleanServer=s=>(s||location.origin).trim().replace(/\/$/,'');
const apiUrl=c=>`${c.server}/api/v1/vaults/${c.vaultId}`;
const nativePending=new Map();let nativeRequestId=0;
window.onAnubisHttp=(id,status,text,error)=>{const p=nativePending.get(id);if(!p)return;nativePending.delete(id);error?p.no(Error(error)):p.ok({ok:status>=200&&status<300,status,data:(()=>{try{return JSON.parse(text)}catch{return{}}})()})};
async function httpJson(url,method,token,body){if(window.AnubisAndroid?.httpRequest){const id=String(++nativeRequestId),text=body?JSON.stringify(body):'';return new Promise((ok,no)=>{nativePending.set(id,{ok,no});window.AnubisAndroid.httpRequest(id,url,method,token,text)})}const r=await fetch(url,{method,headers:{authorization:`Bearer ${token}`,'content-type':'application/json'},body:body?JSON.stringify(body):undefined,cache:'no-store'}),data=await r.json().catch(()=>({}));return{ok:r.ok,status:r.status,data}}
async function request(c,method,body){return httpJson(apiUrl(c),method,c.token,body)}
async function snapshot(){return{meta:await get('meta'),items:await get('items')}}
const canonical=x=>JSON.stringify([...x].sort((a,b)=>a.id.localeCompare(b.id)));
function merge(local,remote){const all=new Map();for(const x of [...local,...remote]){const old=all.get(x.id);if(!old||String(x.updatedAt)>String(old.updatedAt))all.set(x.id,x)}return[...all.values()]}
function setSyncStatus(text,state=''){$('#syncStatus').textContent=text;$('#syncStatus').className=state}
async function syncVault(silent=false){const c=await get('sync');if(!c||!key){setSyncStatus('○ 仅此设备');return}if(syncBusy)return;syncBusy=true;setSyncStatus('↻ 正在同步','syncing');try{let r=await request(c,'GET');if(!r.ok)throw Error(r.data.error||`HTTP ${r.status}`);const remote=await decrypt(r.data.snapshot.items),merged=merge(items,remote),remoteSame=canonical(merged)===canonical(remote);items=merged;if(remoteSame){await put('items',r.data.snapshot.items);c.revision=r.data.revision}else{const box=await encrypt(merged);r=await request(c,'PUT',{baseRevision:r.data.revision,snapshot:{meta:await get('meta'),items:box}});if(r.status===409){const latest=await decrypt(r.data.snapshot.items);items=merge(items,latest);const retry=await request(c,'PUT',{baseRevision:r.data.revision,snapshot:{meta:await get('meta'),items:await encrypt(items)}});if(!retry.ok)throw Error(retry.data.error);c.revision=retry.data.revision}else{if(!r.ok)throw Error(r.data.error);c.revision=r.data.revision}await put('items',await encrypt(items))}await put('sync',c);render();setSyncStatus('● 已同步','synced');if(!silent)toast('所有设备已同步')}catch(e){setSyncStatus('! 同步失败');if(!silent)toast(`同步失败：${e.message}`)}finally{syncBusy=false}}
function scheduleSync(){clearTimeout(syncTimer);syncTimer=setTimeout(()=>syncVault(true),700)}
function pairing(c){return btoa(JSON.stringify({format:'anubis-pair-v1',server:c.server,vaultId:c.vaultId,token:c.token}))}
const hexBytes=s=>Uint8Array.from(s.match(/../g)||[],x=>parseInt(x,16));
async function inviteKey(token){return crypto.subtle.importKey('raw',hexBytes(token),{name:'AES-GCM'},false,['encrypt','decrypt'])}
async function inviteRequest(p,method,body){return httpJson(`${p.server}/api/v1/invites/${p.inviteId}`,method,p.token,body)}
function showPairing(c){const code=pairing(c),qr=qrcode(0,'L');qr.addData(code);qr.make();$('#pairingCode').value=code;$('#pairingQr').src=qr.createDataURL(7,16);$('#syncSetup').classList.add('hidden');$('#syncReady').classList.remove('hidden');$('#serverWrap').classList.add('hidden')}
async function suggestedServer(){if(!['localhost','127.0.0.1'].includes(location.hostname))return location.origin;try{const r=await fetch('/api/v1/discovery',{cache:'no-store'}),x=await r.json();return x.suggestedServer||location.origin}catch{return location.origin}}
async function showSync(){const c=await get('sync');$('#syncServer').value=c?.server||await suggestedServer();$('#syncServer').disabled=!!c;$('#syncSetup').classList.toggle('hidden',!!c);$('#syncReady').classList.toggle('hidden',!c);$('#serverWrap').classList.toggle('hidden',!!c);if(c)showPairing(c);$('#syncDialog').showModal()}
$('#syncBtn').onclick=showSync;document.querySelectorAll('.close-sync').forEach(x=>x.onclick=()=>$('#syncDialog').close());
$('#enableSync').onclick=async()=>{const c={server:cleanServer($('#syncServer').value),vaultId:randomHex(16),token:randomHex(32),revision:0};try{const r=await request(c,'POST',await snapshot());if(!r.ok)throw Error(r.data.error);c.revision=r.data.revision;await put('sync',c);$('#syncServer').disabled=true;showPairing(c);setSyncStatus('● 已同步','synced');toast('二维码已生成，用手机扫描即可')}catch(e){toast(`启用失败：${e.message}`)}};
$('#copyPairing').onclick=async()=>{await navigator.clipboard.writeText($('#pairingCode').value);toast('配对码已复制，请安全传给自己的设备')};$('#syncNow').onclick=()=>syncVault();
$('#joinBtn').onclick=()=>{$('#scanPairing').classList.toggle('hidden',!window.AnubisAndroid?.scanPairing);$('#joinDialog').showModal()};document.querySelectorAll('.close-join').forEach(x=>x.onclick=()=>$('#joinDialog').close());
async function uploadToInvite(p){if(!await get('meta'))throw Error('这台设备还没有保险箱');if(!confirm('把这台设备的保险箱安全发送到电脑？'))return;const c={server:cleanServer(p.server),vaultId:randomHex(16),token:randomHex(32),revision:0},snap=await snapshot(),created=await request(c,'POST',snap);if(!created.ok)throw Error(created.data.error);c.revision=created.data.revision;const payload=await encrypt({sync:c,snapshot:snap},await inviteKey(p.token)),sent=await inviteRequest(p,'PUT',{payload});if(!sent.ok)throw Error(sent.data.error);await put('sync',c);setSyncStatus('● 已同步','synced');toast('已发送到电脑，两端开始自动同步')}
async function joinWithCode(code){try{const p=JSON.parse(atob(code.trim()));if(p.format==='anubis-invite-v1')return await uploadToInvite(p);if(p.format!=='anubis-pair-v1')throw Error('二维码不是 Anubis 配对码');if(await get('meta')&&!confirm('加入会替换本机保险箱，确定继续？'))return;const c={server:cleanServer(p.server),vaultId:p.vaultId,token:p.token,revision:0},r=await request(c,'GET');if(!r.ok)throw Error(r.data.error);c.revision=r.data.revision;await put('meta',r.data.snapshot.meta);await put('items',r.data.snapshot.items);await put('sync',c);toast('连接成功，请输入主密码解锁');setTimeout(()=>location.reload(),800)}catch(e){toast(`连接失败：${e.message}`)}}
$('#joinConfirm').onclick=()=>joinWithCode($('#joinCode').value);$('#scanPairing').onclick=()=>{if(window.AnubisAndroid?.scanPairing)window.AnubisAndroid.scanPairing();else toast('此设备不支持原生扫码，请使用手动配对码')};window.onAnubisScan=code=>{$('#joinDialog').close();joinWithCode(code)};
async function receiveFromPhone(){try{const p={format:'anubis-invite-v1',server:cleanServer(await suggestedServer()),inviteId:randomHex(16),token:randomHex(32)},created=await inviteRequest(p,'POST');if(!created.ok)throw Error(created.data.error);const code=btoa(JSON.stringify(p)),qr=qrcode(0,'L');qr.addData(code);qr.make();$('#receiveCode').value=code;$('#receiveQr').src=qr.createDataURL(7,16);$('#receiveStatus').textContent='等待手机扫码…';$('#receiveDialog').showModal();clearInterval(inviteTimer);inviteTimer=setInterval(async()=>{const r=await inviteRequest(p,'GET');if(r.status!==200)return;clearInterval(inviteTimer);const bundle=await decrypt(r.data.payload,await inviteKey(p.token));await put('meta',bundle.snapshot.meta);await put('items',bundle.snapshot.items);await put('sync',bundle.sync);await inviteRequest(p,'DELETE');$('#receiveStatus').textContent='接收成功，正在打开保险箱…';setTimeout(()=>location.reload(),900)},1200)}catch(e){toast(`无法创建二维码：${e.message}`)}}
$('#receiveBtn').onclick=receiveFromPhone;document.querySelectorAll('.close-receive').forEach(x=>x.onclick=()=>{clearInterval(inviteTimer);$('#receiveDialog').close()});
if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{});
addEventListener('online',()=>syncVault(true));setInterval(()=>syncVault(true),60000);
