'use strict';
let syncBusy=false,syncTimer;
const randomHex=n=>[...crypto.getRandomValues(new Uint8Array(n))].map(x=>x.toString(16).padStart(2,'0')).join('');
const cleanServer=s=>(s||location.origin).trim().replace(/\/$/,'');
const apiUrl=c=>`${c.server}/api/v1/vaults/${c.vaultId}`;
async function request(c,method,body){const r=await fetch(apiUrl(c),{method,headers:{authorization:`Bearer ${c.token}`,'content-type':'application/json'},body:body?JSON.stringify(body):undefined,cache:'no-store'}),data=await r.json().catch(()=>({}));return{ok:r.ok,status:r.status,data}}
async function snapshot(){return{meta:await get('meta'),items:await get('items')}}
const canonical=x=>JSON.stringify([...x].sort((a,b)=>a.id.localeCompare(b.id)));
function merge(local,remote){const all=new Map();for(const x of [...local,...remote]){const old=all.get(x.id);if(!old||String(x.updatedAt)>String(old.updatedAt))all.set(x.id,x)}return[...all.values()]}
function setSyncStatus(text,state=''){$('#syncStatus').textContent=text;$('#syncStatus').className=state}
async function syncVault(silent=false){const c=await get('sync');if(!c||!key){setSyncStatus('○ 仅此设备');return}if(syncBusy)return;syncBusy=true;setSyncStatus('↻ 正在同步','syncing');try{let r=await request(c,'GET');if(!r.ok)throw Error(r.data.error||`HTTP ${r.status}`);const remote=await decrypt(r.data.snapshot.items),merged=merge(items,remote),remoteSame=canonical(merged)===canonical(remote);items=merged;if(remoteSame){await put('items',r.data.snapshot.items);c.revision=r.data.revision}else{const box=await encrypt(merged);r=await request(c,'PUT',{baseRevision:r.data.revision,snapshot:{meta:await get('meta'),items:box}});if(r.status===409){const latest=await decrypt(r.data.snapshot.items);items=merge(items,latest);const retry=await request(c,'PUT',{baseRevision:r.data.revision,snapshot:{meta:await get('meta'),items:await encrypt(items)}});if(!retry.ok)throw Error(retry.data.error);c.revision=retry.data.revision}else{if(!r.ok)throw Error(r.data.error);c.revision=r.data.revision}await put('items',await encrypt(items))}await put('sync',c);render();setSyncStatus('● 已同步','synced');if(!silent)toast('所有设备已同步')}catch(e){setSyncStatus('! 同步失败');if(!silent)toast(`同步失败：${e.message}`)}finally{syncBusy=false}}
function scheduleSync(){clearTimeout(syncTimer);syncTimer=setTimeout(()=>syncVault(true),700)}
function pairing(c){return btoa(JSON.stringify({format:'anubis-pair-v1',server:c.server,vaultId:c.vaultId,token:c.token}))}
function showPairing(c){const code=pairing(c),qr=qrcode(0,'M');qr.addData(code);qr.make();$('#pairingCode').value=code;$('#pairingQr').src=qr.createDataURL(5,12);$('#syncSetup').classList.add('hidden');$('#syncReady').classList.remove('hidden');$('#serverWrap').classList.add('hidden')}
async function suggestedServer(){if(!['localhost','127.0.0.1'].includes(location.hostname))return location.origin;try{const r=await fetch('/api/v1/discovery',{cache:'no-store'}),x=await r.json();return x.suggestedServer||location.origin}catch{return location.origin}}
async function showSync(){const c=await get('sync');$('#syncServer').value=c?.server||await suggestedServer();$('#syncServer').disabled=!!c;$('#syncSetup').classList.toggle('hidden',!!c);$('#syncReady').classList.toggle('hidden',!c);$('#serverWrap').classList.toggle('hidden',!!c);if(c)showPairing(c);$('#syncDialog').showModal()}
$('#syncBtn').onclick=showSync;document.querySelectorAll('.close-sync').forEach(x=>x.onclick=()=>$('#syncDialog').close());
$('#enableSync').onclick=async()=>{const c={server:cleanServer($('#syncServer').value),vaultId:randomHex(16),token:randomHex(32),revision:0};try{const r=await request(c,'POST',await snapshot());if(!r.ok)throw Error(r.data.error);c.revision=r.data.revision;await put('sync',c);$('#syncServer').disabled=true;showPairing(c);setSyncStatus('● 已同步','synced');toast('二维码已生成，用手机扫描即可')}catch(e){toast(`启用失败：${e.message}`)}};
$('#copyPairing').onclick=async()=>{await navigator.clipboard.writeText($('#pairingCode').value);toast('配对码已复制，请安全传给自己的设备')};$('#syncNow').onclick=()=>syncVault();
$('#joinBtn').onclick=()=>{$('#scanPairing').classList.toggle('hidden',!window.AnubisAndroid?.scanPairing);$('#joinDialog').showModal()};document.querySelectorAll('.close-join').forEach(x=>x.onclick=()=>$('#joinDialog').close());
async function joinWithCode(code){try{if(await get('meta')&&!confirm('加入会替换本机保险箱，确定继续？'))return;const p=JSON.parse(atob(code.trim()));if(p.format!=='anubis-pair-v1')throw Error('二维码不是 Anubis 配对码');const c={server:cleanServer(p.server),vaultId:p.vaultId,token:p.token,revision:0},r=await request(c,'GET');if(!r.ok)throw Error(r.data.error);c.revision=r.data.revision;await put('meta',r.data.snapshot.meta);await put('items',r.data.snapshot.items);await put('sync',c);toast('连接成功，请输入主密码解锁');setTimeout(()=>location.reload(),800)}catch(e){toast(`连接失败：${e.message}`)}}
$('#joinConfirm').onclick=()=>joinWithCode($('#joinCode').value);$('#scanPairing').onclick=()=>window.AnubisAndroid?.scanPairing();window.onAnubisScan=code=>{$('#joinDialog').close();joinWithCode(code)};
if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{});
addEventListener('online',()=>syncVault(true));setInterval(()=>syncVault(true),60000);
